### ISSUE TITLE
Incompatibility with Yet Another Prosthetic Core

### ISSUE THREAD

**Issue by MrXarous** [emipa606/ProstheticNoMissingBodyParts#1]
Testing in a vanilla-ish mod list everything worked as expected but adding in Yet Another Prosthetic -- Core mod and having a pawn with two advanced bionic arms no longer allowed them to equip gloves from Vanilla Expanded Armor.

Harmony/Core/Royalty/Ideology/Biotech/HugsLib/ProstheticNoMissingBodyParts/VanillaExpandedFramework/VanillaApparelExpanded/XMLExtensions/YetAnotherProstheticModCore in that order. 

Again PNMBP and VEFramework and Vanilla Apparel Expanded all functioned as it should. 

User Kokorocodon states possibly same issue with Expanded Prosthetic and Organ Engineering (Forked) also tried non-forked EPOE and said that their pawns could not wear gloves or boots. I was not able to have the time to test the other mods, hope it helps.

**Comment by emipa606** [comment]
Tested this and it works as intended. They just need to enable the respective prosthetics in the options first:
![image](https://user-images.githubusercontent.com/6932991/200919695-0449ac74-98b6-42f2-8933-00778cf418d3.png)
